{% set version = "1.14.0" %}
{% set sha256 = "fc361367f0d4b780a868a8833f9f30b9c9f4ac9faea4e6b251db8b4b0398466e" %}

package:
  name: gstreamer
  version: {{ version }}

source:
  fn: gstreamer-{{ version }}.tar.xz
  url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]

requirements:
  build:
    - bison
    - flex
    - glib 2.55.*
    - gobject-introspection
    - m4
    - perl
    - xz 5.2.*
    - gettext
  run:
    - glib 2.55.*

test:
  commands:
    - gst-inspect-1.0 --version
    - gst-launch-1.0  --version
    - gst-stats-1.0 --version
    - gst-typefind-1.0 --version

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL 2
  summary: "Library for constructing graphs of media-handling components"

extra:
  recipe-maintainers:
    - ccordoba12
    - mingwandroid
